---
# Nexus 3 역할 기본 변수 (참고: Continous-integration/Nexus/nexus-env.sh)
nexus_user: nexus
install_dir: /opt
nexus_home: "{{ install_dir }}/nexus-app"
work_dir: "{{ install_dir }}/sonatype-work"
java_package: "java-17-openjdk-devel"
nexus_port: 8081
nexus_download_url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
